image: node

stages:
  - build

eslint:
 stage: build

 script:
   # install eslint
   - npm i eslint
   # Run eslint
   - node_modules/eslint/bin/eslint.js .
 rules:
   - if: $CI_PIPELINE_SOURCE == 'merge_request_event'